-- pll_video_pll_0.vhd

-- This file was auto-generated from altera_up_avalon_video_pll_hw.tcl.  If you edit it your changes
-- will probably be lost.
-- 
-- Generated using ACDS version 23.1 991

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity pll_video_pll_0 is
	port (
		ref_clk_clk        : in  std_logic := '0'; --      ref_clk.clk
		ref_reset_reset    : in  std_logic := '0'; --    ref_reset.reset
		vga_clk_clk        : out std_logic;        --      vga_clk.clk
		reset_source_reset : out std_logic         -- reset_source.reset
	);
end entity pll_video_pll_0;

architecture rtl of pll_video_pll_0 is
	component pll_video_pll_0_video_pll is
		port (
			refclk   : in  std_logic := 'X'; -- clk
			rst      : in  std_logic := 'X'; -- reset
			outclk_0 : out std_logic;        -- clk
			outclk_1 : out std_logic;        -- clk
			outclk_2 : out std_logic;        -- clk
			locked   : out std_logic         -- export
		);
	end component pll_video_pll_0_video_pll;

	component altera_up_avalon_reset_from_locked_signal is
		port (
			reset  : out std_logic;        -- reset
			locked : in  std_logic := 'X'  -- export
		);
	end component altera_up_avalon_reset_from_locked_signal;

	signal video_pll_locked_export : std_logic; -- video_pll:locked -> reset_from_locked:locked

begin

	video_pll : component pll_video_pll_0_video_pll
		port map (
			refclk   => ref_clk_clk,             --  refclk.clk
			rst      => ref_reset_reset,         --   reset.reset
			outclk_0 => open,                    -- outclk0.clk
			outclk_1 => vga_clk_clk,             -- outclk1.clk
			outclk_2 => open,                    -- outclk2.clk
			locked   => video_pll_locked_export  --  locked.export
		);

	reset_from_locked : component altera_up_avalon_reset_from_locked_signal
		port map (
			reset  => reset_source_reset,      -- reset_source.reset
			locked => video_pll_locked_export  --       locked.export
		);

end architecture rtl; -- of pll_video_pll_0
